### ISSUE TITLE
Any way to use SSML or XML voice tags with this gem?

### ISSUE THREAD

**Issue by casper** [djberg96/win32-sapi#1]
I'm trying to figure out how to modify the voice with SSML tags like `<emphasis>`. 

Is there some way this could be done through this gem (or some other way through Ruby)?

**Comment by djberg96** [comment]
Good question @casper. I just tried this:

```
# Based on https://msdn.microsoft.com/en-us/library/ms720163(v=vs.85).aspx
require 'win32/sapi5'
SPF_IS_XML = 4

v = SpVoice.new
v.Speak("This sounds normal <pitch middle = '-10'/> but the pitch drops half way through", SPF_IS_XML)
```

But that did not work, and gave me an error.

@phasis68 Do you have any suggestions?

**Comment by casper** [comment]
Thank you @djberg96! It was easier than I imagined.
8 is the magic number:
https://msdn.microsoft.com/en-us/library/ms720892(v=vs.85).aspx

```
v.Speak("....", 8)
```

**Comment by phasis68** [comment]
Here is the definition of constant

``` C
#define SPF_DEFAULT          0 //not asynchronous
#define SPF_ASYNC            1 // asynchronous
#define SPF_PURGEBEFORESPEAK 2 //Purges all pending speak requests prior to this speak call.
#define SPF_IS_FILENAME      4 //The string passed is a file name, and the file text should be spoken.
#define SPF_IS_XML           8 //The input text will be parsed for XML markup. 
#define SPF_IS_NOT_XML      16 
```

Here is a working code

``` ruby
require 'win32/sapi5'
include Win32
SPF_IS_XML = 8
v = SpVoice.new
v.Speak("This sounds normal <pitch middle = '-10'/> but the pitch drops half way through", SPF_IS_XML)
```

**Comment by djberg96** [comment]
@phasis68 Thank you, I was looking at an invalid enum list apparently. Sorry about that.

@casper Glad you figured it out! We should really add a wiki with a bunch of examples. If you're interested in helping out with that, please let me know and I'll add you to the project.

**Comment by djberg96** [comment]
@casper I've added those constants directly to the SpVoice class and pushed out version 0.2.0. So now you can use SpVoice::SPF_IS_XML, etc.

**Comment by casper** [comment]
Nice. Thanks for the quick help and fix.
